import {
  Accessibility,
  Ambulance,
  Anchor,
  Award,
  Baby,
  Banknote,
  BatteryCharging,
  Bell,
  Bike,
  Book,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  CableCar,
  Calendar,
  Camera,
  Car,
  CarFront,
  CarTaxiFront,
  Castle,
  Cat,
  Check,
  Church,
  CircleParking,
  Clock,
  Coffee,
  Compass,
  CreditCard,
  Crown,
  Dog,
  Droplet,
  Dumbbell,
  Eye,
  Factory,
  Film,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Forklift,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  Helicopter,
  Hospital,
  Hotel,
  House,
  Image,
  Info,
  Key,
  Landmark,
  Leaf,
  Library,
  Lightbulb,
  LocateFixed,
  Lock,
  Mail,
  Map,
  MapPin,
  MapPinned,
  Medal,
  Milestone,
  Mountain,
  Music,
  Navigation,
  Palette,
  PartyPopper,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Plug,
  PlugZap,
  Radar,
  Recycle,
  Rocket,
  Route,
  Sailboat,
  School,
  Search,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Signpost,
  Siren,
  Sparkles,
  SquareParking,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tent,
  ThumbsUp,
  Tractor,
  TrafficCone,
  TrainFront,
  TrainTrack,
  TramFront,
  Trees,
  Trophy,
  Truck,
  Tv,
  Users,
  Utensils,
  Video,
  Warehouse,
  Wallet,
  Waves,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Stored connectivity icon id (kebab-case, picked in the CRM icon picker)
 * → render component. Must stay in sync with the CRM icon library
 * (crm-frontend/src/components/shared/icon-picker.tsx). Unknown ids fall
 * back to Navigation.
 */
const MAP: Record<string, LucideIcon> = {
  bus: Bus,
  train: TrainFront,
  tram: TramFront,
  car: Car,
  "car-front": CarFront,
  taxi: CarTaxiFront,
  bike: Bike,
  plane: Plane,
  "plane-takeoff": PlaneTakeoff,
  "plane-landing": PlaneLanding,
  ship: Ship,
  sailboat: Sailboat,
  anchor: Anchor,
  helicopter: Helicopter,
  rocket: Rocket,
  fuel: Fuel,
  parking: SquareParking,
  "circle-parking": CircleParking,
  truck: Truck,
  ambulance: Ambulance,
  tractor: Tractor,
  forklift: Forklift,
  "cable-car": CableCar,
  "train-track": TrainTrack,
  "traffic-cone": TrafficCone,
  milestone: Milestone,
  signpost: Signpost,
  navigation: Navigation,
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  map: Map,
  compass: Compass,
  locate: LocateFixed,
  radar: Radar,
  globe: Globe,
  route: Route,
  footprints: Footprints,
  flag: Flag,
  landmark: Landmark,
  castle: Castle,
  church: Church,
  hotel: Hotel,
  warehouse: Warehouse,
  building: Building,
  "building-2": Building2,
  house: House,
  store: Store,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  school: School,
  "graduation-cap": GraduationCap,
  hospital: Hospital,
  factory: Factory,
  library: Library,
  wifi: Wifi,
  coffee: Coffee,
  utensils: Utensils,
  dumbbell: Dumbbell,
  tv: Tv,
  music: Music,
  film: Film,
  "gamepad-2": Gamepad2,
  book: Book,
  "book-open": BookOpen,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  trees: Trees,
  leaf: Leaf,
  "flower-2": Flower2,
  sun: Sun,
  waves: Waves,
  mountain: Mountain,
  tent: Tent,
  trophy: Trophy,
  palette: Palette,
  phone: Phone,
  mail: Mail,
  bell: Bell,
  shield: Shield,
  "shield-check": ShieldCheck,
  siren: Siren,
  briefcase: Briefcase,
  banknote: Banknote,
  "credit-card": CreditCard,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  plug: Plug,
  "plug-zap": PlugZap,
  wrench: Wrench,
  hammer: Hammer,
  lightbulb: Lightbulb,
  droplet: Droplet,
  flame: Flame,
  zap: Zap,
  "battery-charging": BatteryCharging,
  recycle: Recycle,
  pill: Pill,
  stethoscope: Stethoscope,
  clock: Clock,
  calendar: Calendar,
  users: Users,
  accessibility: Accessibility,
  check: Check,
  info: Info,
  search: Search,
  eye: Eye,
  camera: Camera,
  image: Image,
  video: Video,
  award: Award,
  medal: Medal,
  crown: Crown,
  gem: Gem,
  key: Key,
  lock: Lock,
  gift: Gift,
  "party-popper": PartyPopper,
  "thumbs-up": ThumbsUp,
};

export function connectivityIconFor(value?: string | null): LucideIcon {
  if (value && ALIASED[value]) return ALIASED[value];
  return Navigation;
}

const toPascal = (kebab: string): string =>
  kebab
    .split("-")
    .map((p) => (p ? p.charAt(0).toUpperCase() + p.slice(1) : p))
    .join("");

/** Legacy kebab ids plus their PascalCase forms ("bus" and "Bus" both work).
 *  Icons picked from outside the curated set fall back to Navigation. */
const ALIASED: Record<string, LucideIcon> = { ...MAP };
for (const [k, v] of Object.entries(MAP)) {
  const pascal = toPascal(k);
  if (!ALIASED[pascal]) ALIASED[pascal] = v;
}
